version: '3.8'

services:
  backend:
    build:
      context: ./apiary
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  
  # frontend:
  #   build:
  #     context: ./apiaryFrontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4200:4200"
    