apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-apiary-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-apiary
  template:
    metadata:
      labels:
        app: angular-apiary
    spec:
      containers:
      - name: angular-apiary-deployment
        image: remmo1/apiary-frontend:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 4200
        env:
          - name: HIVE_URL
            valueFrom:
              configMapKeyRef:
                name: angular-config-map
                key: hive
          - name: SEASON_URL
            valueFrom:
              configMapKeyRef:
                name: angular-config-map
                key: season
---
apiVersion: v1
kind: Service
metadata:
 name: angular-apiary-service
spec:
 selector:
   app: angular-apiary
 ports:
 - port: 4200
   targetPort: 4200
   protocol: TCP
